# Generated by Django 2.0.3 on 2018-03-30 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_sheet', '0002_auto_20180330_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusicsheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='musicsheetcomments',
            name='music_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_sheet.Music_sheet', verbose_name='歌单'),
        ),
        migrations.AddField(
            model_name='musicsheetcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
