# Generated by Django 2.0.3 on 2018-03-12 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_sheet',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='music_sheet',
            name='sheet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_sheet.TypeDict', verbose_name='歌单类型'),
        ),
    ]
