# Generated by Django 2.0.3 on 2018-03-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sheet', '0002_auto_20180330_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='歌曲编号'),
        ),
    ]
