# Generated by Django 2.0.3 on 2018-03-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_sheet', '0002_auto_20180312_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='songs_detail',
            new_name='song_detail',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='songs_resourse',
            new_name='song_resourse',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='songs_type',
            new_name='song_type',
        ),
    ]
