# Generated by Django 2.0.3 on 2018-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sheet', '0003_auto_20180312_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(default='匿名歌手', max_length=50, verbose_name='歌手'),
        ),
    ]
