# Generated by Django 2.0.3 on 2018-04-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_sheet', '0004_auto_20180402_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='singer_name',
        ),
    ]
