# Generated by Django 2.0.3 on 2018-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sheet', '0004_auto_20180316_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='singer_name',
            field=models.CharField(default='匿名歌手', max_length=50, verbose_name='歌手'),
        ),
    ]
