# Generated by Django 2.0.3 on 2018-04-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_sheet', '0005_remove_songs_singer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='singer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_sheet.Singer', verbose_name='歌手'),
        ),
    ]
