# Generated by Django 2.0.3 on 2018-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sheet', '0006_songs_singer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_sheet',
            name='songs',
            field=models.ManyToManyField(to='music_sheet.Songs', verbose_name='歌曲'),
        ),
    ]
