# Generated by Django 2.0.3 on 2018-03-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180316_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='', max_length=100, verbose_name='关于'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.TextField(default='', verbose_name='个人信息'),
        ),
    ]
