# Generated by Django 2.0.3 on 2018-03-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180318_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='this person is very lazy', max_length=100, verbose_name='关于'),
        ),
    ]
